name: dbt_airflow

config-version: 2

profile: profiles

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  dbt_airflow:
    +materialized: table
    raw:
      +materialized: incremental
      +incremental_strategy: append
      +schema: raw
    staging:
      +materialized: view
      +schema: staging
    # intermediate:
    #   +materialized: table
    #   +schema: intermediate
    marts:
      +materialized: incremental
      +incremental_strategy: delete+insert
      +schema: marts