# profiles.yml
profiles:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: db_in_ch
      host: localhost
      port: 8123
      user: default
      password: ''
      secure: False