CREATE DATABASE IF NOT EXISTS postgres ON CLUSTER 'cluster_2S_2R';
CREATE DATABASE IF NOT EXISTS raw ON CLUSTER 'cluster_2S_2R';
CREATE DATABASE IF NOT EXISTS staging ON CLUSTER 'cluster_2S_2R';
CREATE DATABASE IF NOT EXISTS intermediate ON CLUSTER 'cluster_2S_2R';
CREATE DATABASE IF NOT EXISTS marts ON CLUSTER 'cluster_2S_2R';