CREATE DATABASE IF NOT EXISTS bronze ON CLUSTER 'cluster_2S_2R';
CREATE DATABASE IF NOT EXISTS silver ON CLUSTER 'cluster_2S_2R';
CREATE DATABASE IF NOT EXISTS gold ON CLUSTER 'cluster_2S_2R';
CREATE DATABASE IF NOT EXISTS data_mart ON CLUSTER 'cluster_2S_2R';
CREATE DATABASE IF NOT EXISTS bi ON CLUSTER 'cluster_2S_2R';