FROM apache/airflow:3.1.3-python3.12

USER root

WORKDIR /opt/airflow
COPY requirements.txt .
COPY .env .

USER airflow
RUN pip install --no-cache-dir -r requirements.txt

ENV PATH="$JAVA_HOME/bin:$PATH"
ENV PYTHONPATH="/opt/airflow:/opt/airflow/dags:/opt/airflow/plugins"