name: dbt_project

config-version: 2

profile: profiles

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  dbt_project:
    +materialized: table
    utils:
      +materialized: table
      +schema: utils
    staging:
      +materialized: table
      +schema: staging
      +engine: MergeTree
    # intermediate:
    #   +materialized: table
    #   +schema: intermediate
    marts:
      +materialized: incremental
      +incremental_strategy: delete+insert
      +schema: marts