profiles:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: default
      host: localhost
      port: 8123
      user: default
      password: ''
      secure: False
    
    prod:
      type: clickhouse
      schema: default
      host: "{{ env_var('DBT_CLICKHOUSE_HOST') }}"
      port: "{{ env_var('DBT_CLICKHOUSE_PORT') | int }}"
      user: "{{ env_var('DBT_CLICKHOUSE_USER') }}"
      password: "{{ env_var('DBT_CLICKHOUSE_PASSWORD') }}"
      secure: False